In [1]:
import numpy as np

In [2]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [10]:
def create(l):
    for i in range(5):
        n = int(input())
        l.append(n)
    return l
l1=[]
l2=[]
print(create(l1))
print(create(l2))

4
5
1
0
8
[4, 5, 1, 0, 8]
2
7
3
6
9
[2, 7, 3, 6, 9]


In [11]:
l1=np.array(l1)
l2=np.array(l2)

In [14]:
arr=np.concatenate([l1,l2])
arr

array([4, 5, 1, 0, 8, 2, 7, 3, 6, 9])

In [18]:
np.sort(l1)

array([0, 1, 4, 5, 8])

In [19]:
np.sort(l2)

array([2, 3, 6, 7, 9])

In [20]:
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

multidimensional array

In [21]:
np.ndim(arr)

1

In [22]:
print(arr.size)

10


In [23]:
arr=np.arange(25).reshape(5,5)

In [26]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
np.ndim(arr)

2

In [27]:
arr.size

25

convert 1d array to 2d

In [37]:
arr= np.arange(12)

In [38]:
np.ndim(arr)

1

In [39]:
arr=np.expand_dims(arr,axis=1)
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [40]:
np.ndim(arr)

2

In [79]:
np.newaxis is None

True

In [55]:
arr1 = np.arange(16).reshape(4,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
arr2 = np.arange(17,33).reshape(4,4)
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [58]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [59]:
np.hstack((arr1,arr2))

array([[ 0,  1,  2,  3, 17, 18, 19, 20],
       [ 4,  5,  6,  7, 21, 22, 23, 24],
       [ 8,  9, 10, 11, 25, 26, 27, 28],
       [12, 13, 14, 15, 29, 30, 31, 32]])

to get unique items and count of unique items

In [70]:
arr=np.array([[1,6,1,2,5,3,6],[2,7,0,9,1,4,7]])
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [75]:
unique_ele, counts_unique = np.unique(arr, return_counts=True)

In [76]:
counts_unique

array([1, 3, 2, 1, 1, 1, 2, 2, 1], dtype=int64)

In [77]:
np.asarray((unique_elements, counts_unique))

array([[0, 1, 2, 3, 4, 5, 6, 7, 9],
       [1, 3, 2, 1, 1, 1, 2, 2, 1]], dtype=int64)

# ThankYou!